### ISSUE TITLE
Create a terms of service document for Syftorium and Specify cache

### ISSUE THREAD

**Issue by cjgrady** [lifemapper/lmsyft#16]
@cjgrady will set up the initial document and probably cut and paste a lot of it from Lifemapper.

We will need other eyes on it to be sure it covers what we need / want it to.   Assigning @beach53 and @zzeppozz too and will notify when ready for edits / evaluation.

**Comment by beach53** [comment]
A few questions come to mind:
1) what public access are we envisioning that would require a document like this? Or what are the other usages that legally require a legal statement.
2) the benefits of this cache, in whatever uses we create for it will accrue to the members of the SCC, with which we have a legal Membership Agreement signed by them and us.  This could fall into the terms and conditions of membership in the SCC and might be made explicit in the membership documents.  We will need advice from the KU attorney about the issues here.
3) non SCC related publishing to aggregators like idigbio and GBIF must have some legalish documents associated with them we can look at that.  I know GBIF encourages the providers to post their conditions for re-use of their data by third parties getting the data from GBIF fore example but don't know if GBIF itself and the provider have legal covenants.

**Comment by beach53** [comment]
Will be thinking on it and poking around ...

**Comment by cjgrady** [comment]
I think that we want to have some specifications for how people should cite anything they use, be that a specific occurrence record like they would do through GBIF or iDigBio, or our Syftorium analyses that we perform.

It sounds like SCC is going to complicate this-- possibly a lot.

**Comment by cjgrady** [comment]
From a general standpoint, we don't legally have to have one.  That may not be true for SCC though.

**Comment by beach53** [comment]
A lot of good questions here.  I suspect there is a lot of cribbing with TOS agreements, so I propose (above) that we look at what other people have done, in particular the aggregators for statements as models. In general this community appears to have little concerned about restricting use of their data beyond the expectation for (1) attribution and then ultimately digital feedback. The Syftorium might be the perfect place to put a feedback mechanism in for sending snippets back to Specify as we control both ends and we can experiment easily without waiting for anyone to agree.  We had the same idea for snippets from Lifemapper.  What would next steps for that be?  Creating an attribution API in Specify 7?  What would we send it, raw attribution data or summarized attribution data condensed by a Syftorium service?

**Comment by cjgrady** [comment]
This TOS seems good to me for now.  We'll need to update it when we add additional services but it seems very appropriate for the Specify cache that we are currently exposing.
