### ISSUE TITLE
Add cron job for running process_dwca.py in deployment rolls

### ISSUE THREAD

**Issue by cjgrady** [lifemapper/lmsyft#22]
I have it set to run hourly on 195 for the `lmwriter` user.

`0 * * * * /opt/python/bin/python3.6 /opt/lifemapper/lmsyft/flask_app/sp_cache/process_dwca.py /state/partition1/lmlab/syftorium_data/new_dwcas/ /state/partition1/lmlab/syftorium_data/processed_dwcas/`

**Comment by cjgrady** [comment]
This requires that the PYTHONPATH environment variable be set correctly.  Alternatively, the script can add /opt/lifemapper/ at run time.

**Comment by cjgrady** [comment]
We decided that we would just use a script and put it in cron.hourly.  CJ started it and it is in `cron/process_dwcas.sh.in`.  Aimee will correct it and populate the variables.

**Comment by zzeppozz** [comment]
Roll will fill vars and install.  Script is present on 195 aka dev.syftorium.org
