### ISSUE TITLE
Utilize a .in file for machine dependent constants

### ISSUE THREAD

**Issue by cjgrady** [lifemapper/lmsyft#24]
Separate the constants file into sections in case we need to pull them apart later (for example, move the resolver code).  Template things like FQDN, ports, and file paths.

**Comment by cjgrady** [comment]
This file is at `lmsyft/flask_app/config/constants.py.in` and awaiting @zzeppozz magic

**Comment by zzeppozz** [comment]
Done and moved to lmsyft/config/constants.py.in.  Roll build and install will fill vars.
