### ISSUE TITLE
Syftorium has some records in specify cache that are not in specify resolver

### ISSUE THREAD

**Issue by zzeppozz** [lifemapper/lmsyft#41]
Development machine (notyeti-195) 
Specify Cache: has 1484892 records.
curl http://localhost:8983/solr/specimen_records/select?q=identifier:bffe655b-ea32-4838-8e80-a80e391d5b11

Specify resolver: has 1484417 records.
 curl http://localhost:8983/solr/spcoco/select?q=id:bffe655b-ea32-4838-8e80-a80e391d5b11

Production machine:
cache has 53192 records 
resolver has 51947 records

**Comment by zzeppozz** [comment]
I think this can be resolved if records are just re-posted, but we probably need some tools to test and re-sync if things get out of whack.

**Comment by zzeppozz** [comment]
I think the bugfix pushed (and in place on syft and syft-dev) for issue #43 will fix the root of this problem

**Comment by cjgrady** [comment]
It seems to be from leftover garbage data.  I cleared the index on both machines and repopulated and now the numbers match.
